[package]
name    = "examples2d"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]
edition = "2018"

[features]
parallel = [ "nphysics_testbed2d/parallel"]

[dependencies]
Inflector  = "0.11"
nalgebra   = "0.21"
ncollide2d = "0.23"
nphysics2d = "0.15"
nphysics_testbed2d = { version = "0.8", features = [ "fluids" ] }

[dependencies.salva2d]
path = "../build/salva2d"
features = [ "nphysics", "sampling" ]

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4"

[target.wasm32-unknown-emscripten.dependencies]
stdweb = "0.4"

[target.asmjs-unknown-emscripten.dependencies]
stdweb = "0.4"

[[bin]]
name = "all_examples2"
path = "./all_examples2.rs"

[[bin]]
name = "fluids2"
path = "basic2.rs"
